### ISSUE TITLE
Please add this to Grafana community plugins

### ISSUE THREAD

**Issue by abhijoshi2k-2** [akamai/akamai-insights-datasource#4]
As Akamai's customer, we would like to use this plugin.
However, we face issue as Grafana cloud does not allow us to add unsigned/private plugins.

Can we have this plugin on Grafana plugins section?

**Comment by 1583669804** [comment]
i also have the same request

**Comment by ppozniak-akamai** [comment]
Hello, 
to be able to use unsigned plugins you need to modify your grafana.ini and add this plugin in grafana.ini file in allow_loading_unsigned_plugins property (https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#allow_loading_unsigned_plugins).
This line needs to be added:
allow_loading_unsigned_plugins=akamai-insights-datasource

**Comment by ppozniak-akamai** [comment]
We are in the middle of signing process. Unfortunately at that moment this is the limitation. I will keep you posted.

**Comment by illrill** [comment]
+1, also want this plugin for [Grafana Cloud](https://grafana.com/grafana/plugins/all-plugins/) and for [Azure Managed Grafana](https://learn.microsoft.com/en-us/azure/managed-grafana/how-to-manage-plugins)

**Comment by ppozniak-akamai** [comment]
Hi,
After discussing with the Grafana team, we’ve decided not to proceed with signing this plugin at this time.
If you encounter any issues installing the plugin, you can easily set up a Grafana instance with the Akamai Insights plugin pre-installed through the Akamai Marketplace. 
Simply follow this link for guidance: [Akamai Marketplace - Grafana Guide](https://www.linode.com/docs/marketplace-docs/guides/prometheus-grafana/#akamai-insights-datasource-plugin-optional).

**Comment by ppozniak-akamai** [comment]
Based on above at the moment we are not planning to sign plugin. Closing the ticket.
