### ISSUE TITLE
Filter operators do not match current spec

### ISSUE THREAD

**Issue by arvidsnet** [akamai/akamai-insights-datasource#8]
according to reporting API v2 docs at https://techdocs.akamai.com/reporting/v2/reference/use-filters the following filter operators are supported:
MATCH_REGEXP
NOT_MATCH_REGEXP
BEGINS_WITH
NOT_BEGINS_WITH
ENDS_WITH
NOT_ENDS_WITH
CONTAINS
NOT_CONTAINS
EXACT
IN_LIST

and it does not match operators defined in akamai-insights-datasource (https://github.com/akamai/akamai-insights-datasource/blob/fab9efb14c809b385cdcf581fb17314b5946e9b0/src/components/query-editor/DataSourceForm/FormTypes.ts#L29)

**Comment by mikeZuber** [comment]
@arvidsnet Thanks for catching this, issue is fixed in version 1.0.1
https://github.com/akamai/akamai-insights-datasource/commit/d9917734cc5cbd49e1c03099acc5c76642661c6f
